apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:3.0.2
        imagePullPolicy: Always
        name: mongo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
      restartPolicy: Always
