apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: gcr.io/assignment2-205312/server:v1
        name: server
        imagePullPolicy: Always
      restartPolicy: Always
