apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: twitter
  name: twitter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
      - image: gcr.io/assignment2-205312/twitter:v1
        name: twitter
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
