apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "8023"
    port: 8023
    targetPort: 15672
  - name: "5672"
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
status:
  loadBalancer: {}
